---
# Creates ec2 instance, then installs LAMP stack in it. Follows up with a current WordPress install complete with theme.

- hosts: localhost
  connection: local
  
  vars:
    awsregion: us-east-1
    instancesize: t2.micro
    instancename: webserver01
    keypair: ec2-ol-mgt
    amitouse: ami-22ce4934
    
    tasks:
      - name: Launch ec2 instance
        ec2:
          key_name: "{{keypair}}"
          instance_type: "{{instancesize}}"
          image: "{{amitouser}}"
          wait: yes
          group: webservers
          count: {{numberofservers}}
          vpc_subnet_id: "{{subnettolaunchin}}"
          assign_public_ip: yes
          state: present
          instance_tags:
             Name: "{{instancename}}"
             Application: webservers
        register: ec2
             
       - name: Wait until port 22 becomes active
         local_action: wait_for host={{ item.public_ip }} port=22 state=started
         with_items: "{{ ec2.instances }}"
       
       - name: Force refresh inventory
         meta: refresh_inventory
