---
- hosts: localhost
  connection: local
  #  strategy: debug
  gather_facts: no
  vars:
    resgrp: gjptmpl
    
  tasks:
      #    - name: Create a resource group
      #azure_rm_resourcegroup:
      #  name: "{{ resgrp }}"
      #  location: eastus

    - name: Create Azure Deploy
      azure_rm_deployment:
        state: present
        resource_group_name: "{{ resgrp }}"
        template_link: winrm.json
        parameters_link: winrm.json

