---
- hosts: localhost
  connection: local
  #  strategy: debug
  gather_facts: no
  vars:
    resgrp: gpryzby
    azure_offer: SQL2012SP3-WS2012R2
    azure_publisher: MicrosoftSQLServer
    
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resgrp }}"
        location: eastus

    - name: create CRM virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resgrp }}"
        name: "{{ resgrp }}-vnet"
        address_prefixes: "192.168.168.0/24"
    
    - name: add CRM subnet
      azure_rm_subnet:
        resource_group: "{{ resgrp }}"
        name: "{{ resgrp }}-subnet"
        address_prefix: "192.168.168.0/24"
        virtual_network: "{{ resgrp }}-vnet"

    - name: create virtual machine
      azure_rm_virtualmachine:
        admin_username: crm
        admin_password: SpaceGhost!!1
        name: "{{ resgrp }}"
        open_ports:
          - 22
          - 80
          - 443
          - 3389
          - 5986 
        os_type: Windows
        public_ip_allocation_method: Static
        resource_group: "{{ resgrp }}"
        state: present
        started: True
        vm_size: Standard_DS11_v2
        image:
          offer: "{{ azure_offer }}"
          publisher: "{{ azure_publisher }}"
          sku: standard
          version: latest

    - name: return from Azure create
      debug:
        var: azure_vm

