---
- hosts: localhost
  connection: local
  #  strategy: debug
  gather_facts: no
  vars:
    resgrp: gpryzby
    
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resgrp }}"
        location: eastus

    - name: Create Azure Deploy
      azure_rm_deployment:
        state: present
        resource_group_name: "{{ resgrp }}"
        template_link: winrm.jason
        parameters_link: winrm.jason

    - name: return from Azure create
      debug:
        var: azure_vm

