---
- hosts: localhost
  connection: local
  #  strategy: debug
  gather_facts: no
  vars:
    resgrp: gjptmpl
    
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resgrp }}"
        location: westus

    - name: Create Azure Deploy
      azure_rm_deployment:
        state: present
        resource_group_name: "{{ resgrp }}"
        parameters:
          adminUsername:
            value: 'crm'
          adminPassword:
            value: 'SpaceGhost!!1'
          dnsLabelPrefix:
            value: 'crm'
          vmName:
            value: 'crm'
          nicName:
            value: 'crm'
          virtualNetworkName:
            value: 'crm'
          publicIPAddressName:
            value: 'crm'
          subnetName:
            value: 'crm'
        template_link: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-vm-winrm-windows/azuredeploy.json'
  #      template_link: 'https://raw.githubusercontent.com/gpryzby/demo-ansible/CRM/CRM/files/w2k12-ssql.json'
  #      parameters_link: 'https://raw.githubusercontent.com/gpryzby/demo-ansible/CRM/CRM/files/w2k12-ssql.parameters.json'
