---
- hosts: localhost
  connection: local
  #  strategy: debug
  gather_facts: no
  vars:
    resgrp: gjptmpl
    
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resgrp }}"
        location: westus

    - name: Create Azure Deploy
      azure_rm_deployment:
        state: present
        resource_group_name: "{{ resgrp }}"
        template_link: https://raw.githubusercontent.com/gpryzby/demo-ansible/CRM/CRM/files/winrm.json
        parameters_link: https://raw.githubusercontent.com/gpryzby/demo-ansible/CRM/CRM/files/winrm.parameters.json

