---
- hosts: all
  gather_facts: no 

  tasks:
    - name: Install and configure CRM
      win_shell: C:\Windows\Temp\CRM-2013\SetupServer.exe /Q /L C:\Windows\Temp\CRM-2013\CRM2013-install.log /config C:\Windows\Temp\crm2013.xml 
