---
- hosts: all
  gather_facts: no 

  tasks:
    - name: Install and configure CRM
      win_command: "C:\\Windows\\Temp\\CRM-2013\\SetupServer.exe //Q //L C:\\Windows\\Temp\\crm.log //config c:\\Windows\\Temp\\crm2013.xml"
