---
- hosts: all
  gather_facts: no

  tasks:
    - name: Install AD features
      win_feature: 
        name: AD-domain-services
        state: present
        include_management_tools: true
        restart: true

    - name: Make a domain controller
      win_domain_controller:
        dns_domain_name: tscrm.local
        domain_admin_user: crm
        domain_admin_password: SpaceGhost!!1
        safe_mode_password: SpaceGhost!!1
        state: domain_controller
        log_path: c:\ansible_win_domain_controller.txt
      register: update_result

    - name: reboot if needed
      win_reboot:
      when: update_result.reboot_required
