---
- hosts: all
  gather_facts: no

  tasks:
    - name: Install AD features
      win_feature: 
        name: AD-domain-services
        state: present
        include_management_tools: true
        restart: true

    - name: Make a forest
      win_shell: Install-ADDSForest -CreateDnsDelegation:$false -DatabasePath "C:\Windows\NTDS" -DomainMode "Win2012R2" -DomainName "tscrm.local" -DomainNetBIOSName "TSCRM" -ForestMode "Win2012R2" -InstallDns:$true -LogPath "C:\Windows\NTDS" -SysvolPath "C:\Windows\SYSVOL" -Force:$true -SafeModeAdministratorPassword (convertto-securestring "SpaceGhost!!1" -asplaintext -force)
      register: update_result

    - name: reboot if needed
      win_reboot:
      when: update_result.reboot_required
