---
- hosts: all
  gather_facts: 

  tasks:
    - name: Copy powershell script to host
      win_copy:
        src: Deploy-Active-Directory.ps1
        dest: C:\Windows\Deploy-Active-Directory.ps1

    - name: Install and configure Active Directory
      win_shell: c:\Windows\Deploy-Active-Directory.ps1
