---
- hosts: all
  gather_facts: no

  tasks:
    - name: Start MSSQLServerOLAPService
      win_service:
        name: MSSQLServerOLAPService
        state: started
        username: TSCRM\crm
        password: SpaceGhost!!1

    - name: stop MSSQLServerOLAPService
      win_service:
        name: MSSQLServerOLAPService
        state: stopped

    - name: Reboot so MSSQLServerOLAPService started as default user
      win_reboot:

    - name: Copy file to setup report server
      win_copy:
        src: Deploy-ReportServer.ps1
        dest: C:\Windows\Temp\Deploy-ReportServer.ps1

    - name: Run script to setup report server
      win_shell: C:\Windows\Temp\Deploy-ReportServer.ps1
