---
- hosts: all
  gather_facts: no

  tasks:
    - name: Start service as local user
      win_service:
        name: MSSQLServerOLAPService
        state: started
        username: TSCRM\crm
        password: SpaceGhost!!1

    - name: reboot
      win_reboot:
