---
- hosts: all
  gather_facts: no

  tasks:
    - name: Copy powershell AD deploy
      win_copy:
        src: Deploy-Active-Directory.ps1
        dest: C:\Windows\Temp\Deploy-Active-Directory.ps1

    - name: Install and configure Active Directory
      win_shell: c:\Windows\Temp\Deploy-Active-Directory.ps1

    - name: Reboot
      win_shell: shutdown /r /t 5

    - name: Copy powershell AD configure
      win_copy:
        src: Configure-Active-Directory.ps1
        dest: C:\Windows\Temp\Configure-Active-Directory.ps1

    - name: Install and configure Active Directory
      win_shell: c:\Windows\Temp\Configure-Active-Directory.ps1

    - name: Reboot
      win_command: shutdown /r /t 5

    - name: Copy powershell AD add users/ou
      win_copy:
        src: Add-Active-Directory.ps1
        dest: C:\Windows\Temp\Add-Active-Directory.ps1

    - name: Install and configure Active Directory
      win_shell: c:\Windows\Temp\Add-Active-Directory.ps1
