---
- hosts: all
  gather_facts: no

  vars:
    crm_domain: TSCRM
    azure_admin_password: 'SpaceGhost!!1'

  tasks:
    - name: Start MSSQLServerOLAPService
      win_service:
        name: MSSQLServerOLAPService
        state: started
        username: '{{ crm_domain }}\crm'
        password: '{{ azure_admin_password }}'

    - name: stop MSSQLServerOLAPService
      win_service:
        name: MSSQLServerOLAPService
        state: stopped

      #- name: Reboot so MSSQLServerOLAPService started as default user
      #win_reboot:

    - name: Copy file to setup report server
      win_copy:
        src: Deploy-ReportServer.ps1
        dest: C:\Windows\Temp\Deploy-ReportServer.ps1

    - name: Run script to setup report server
      win_shell: C:\Windows\Temp\Deploy-ReportServer.ps1
