---
- hosts: all
  gather_facts: 

  tasks:
    - name: Copy powershell script to host
      win_copy:
        src: Deploy-CRM.ps1
        dest: C:\Windows\Deploy-CRM.ps1

    - name: Copy config script to host
      win_copy:
        src: crm2012.xml
        dest: C:\Windows\crm2012.xml

    - name: Install and configure CRM
      win_shell: c:\Windows\Deploy-CRM.ps1
