---
- hosts: all
  gather_facts: no

  tasks:
    - name: Start service as local user
      win_service:
        name: MSSQLServerOLAPService
        state: started
        username: TSCRM\crm.admin
        password: SpaceGhost!!1

    - name: stop service as local user
      win_service:
        name: MSSQLServerOLAPService
        state: stopped

    - name: restart service as local user
      win_service:
        name: MSSQLServerOLAPService
        state: started
        username: NT Service\ReportServer

    - name: Copy file to setup report server
      win_copy:
        src: Deploy-ReportServer.ps1
        dest: C:\Windows\Temp\Deploy-ReportServer.ps1

    - name: Run script to setup report server
      win_shell: C:\Windows\Temp\Deploy-ReportServer.ps1
