---
# Creates azure instance with SQL server already installed

- hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    azure_location: eastus
    azure_vm_size: Standard_DS11_v2
    azure_name: ts-crtm
    azure_keypair: ec2-ol-mgt
    azure_offer: SQL2012SP3-WS2012R2
    azure_publisher: MicrosoftSQLServer
    
  tasks:
      - name: Deploy azure instance
        azure_rm_virtualmachine:
        resource_group: Testing
        name: "{{ azure_name }}"
        vm_size: "{{ azure_vm_size }}"
        admin_username: chouseknecht
        ssh_password: false
        ssh_public_keys: "{{ ssh_keys }}"
        image:
          offer: "{{ azure_publisher }}"
          publisher: "{{ azure_publisher }}"
          sku: standard
          version: latest
        register: azure-inst
             
      - name: Wait until port 22 becomes active
        local_action: wait_for host={{ item.public_ip }} port=22 state=started
        with_items: "{{ azure-inst.instances }}"
       
      - name: Force refresh inventory
        meta: refresh_inventory
