---
- hosts: all
  gather_facts: no

  tasks:
    - name: Install IIS features
      win_feature: 
        name: Application-Server,AS-Web-Support,AS-HTTP-Activation,AS-NET-45-Framework,Web-Server,Web-Mgmt-Tools,Web-Mgmt-Service
        state: present
        include_management_tools: true
        restart: true
