---
- hosts: all
  gather_facts: no

  vars:
    azure_admin_password: 'SpaceGhost!!1'
    crm_domain: TSCRM
    crm_extenstion: local

  tasks:
    - name: Install Windows-Features for Active Directory
      win_feature: 
        name: AD-domain-services
        state: present
        include_management_tools: true
        restart: true

    - name: Create a new domain in Active Directory
      win_domain:
        dns_domain_name: '{{ crm_domain }}.{{ crm_extenstion }}'
        safe_mode_password: '{{ azure_admin_password }}'
      register: update_results

    - name: Reboot if needed
      win_reboot:
      when: update_results.reboot_required

    - name: Make a new domain controller in Active Directory
      win_domain_controller:
        dns_domain_name: '{{ crm_domain }}.{{ crm_extenstion }}'
        domain_admin_user: 'crm@{{ crm_domain }}.{{ crm_extenstion }}'
        domain_admin_password: '{{ azure_admin_password }}'
        safe_mode_password: '{{ azure_admin_password }}'
        state: domain_controller
        log_path: c:\ansible_win_domain_controller.txt
      register: update_results

    - name: Reboot if needed
      win_reboot:
      when: update_results.reboot_required

    - name: Copy powershell script to create a user and organizational unit (OU)
      win_copy:
          src: active-directory-add.ps1
          dest: C:\Windows\Temp\create_ad.ps1
      
    - name: Run powershell script to create user and OU
      win_shell: C:\Windows\Temp\create_ad.ps1
