---
# Creates azure instance with SQL server already installed

- hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: '{{ azure_resgrp }}'
        location: '{{ azure_location }}'

    - name: Create Azure Deploy
      azure_rm_deployment:
        resource_group_name: '{{ azure_resgrp }}'
        parameters:
          adminUsername:
            value: '{{ azure_admin_username }}'
          adminPassword:
            value: '{{ azure_admin_password }}'
          dnsLabelPrefix:
            value: '{{ azure_vm_name }}'
          vmName:
            value: '{{ azure_vm_name }}'
          publicIPAddressName: 
           value: '{{ azure_pubip_name }}'
          virtualNetworkName: 
            value: '{{ azure_vnet }}'
          subnetName: 
            value: '{{ azure_snet }}'
        template_link: 'https://raw.githubusercontent.com/gpryzby/demo-ansible/CRM/CRM/files/sqlserver-deploy.json'
        state: present
      register: az_instance

    - name: Public IP
      debug:
          var: az_instance.deployment.instances[0].ips[0].public_ip
