---
- hosts: all
  gather_facts: no

  tasks:
    - name: Install AD features
      win_feature: 
        name: AD-domain-services
        state: present
        include_management_tools: true
        restart: true

    - name: Make a domain 
      win_domain:
        dns_domain_name: tscrm.local
        safe_mode_password: SpaceGhost!!1
      register: update_results

    - name: reboot if needed
      win_reboot:
      when: update_results.reboot_required

    - name: Make a domain controller
      win_domain_controller:
        dns_domain_name: tscrm.local
        domain_admin_user: crm@tscrm.local
        domain_admin_password: SpaceGhost!!1
        safe_mode_password: SpaceGhost!!1
        state: domain_controller
        log_path: c:\ansible_win_domain_controller.txt
      register: update_results

    - name: reboot if needed
      win_reboot:
      when: update_results.reboot_required

    - name: Copy file to add user and OU to AD
      win_copy:
          src: active-directory-add.ps1
          dest: C:\Windows\Temp\ad-add.ps1
      
    - name: Run PS1 script to add user and OU
      win_shell: C:\Windows\Temp\ad-add.ps1
