---
- hosts: tag_Application_bpm
  become: True
  become_user: root
  gather_facts: no

  vars:
    was_user_name: was

  tasks:
      #    - name: Install WebSphere Application Server

    - name: Set limits for the WAS user
      blockinfile:
        path: /etc/security/limits.conf
        insertbefore: # End of file
        block: |
          # - stack - maximum stack size (KB)
          "{{ was_user_name }}" soft stack 32768
          "{{ was_user_name }}" hard stack 32768
          # - nofile - maximum number of open files
          "{{ was_user_name }}" soft nofile 65536
          "{{ was_user_name }}" hard nofile 65536
          # - nproc - maximum number of processes
          "{{ was_user_name }}" soft nproc 16384
          "{{ was_user_name }}" hard nproc 16384
          # - fsize - maximum file size
          "{{ was_user_name }}" soft fsize 6291453
          "{{ was_user_name }}" hard fsize 6291453

    - name: If the files exists, set the nproc 
      blockinfile:
        path: "{{ item }}"
        block: |
          # - nproc - maximum number of processes
          "{{ was_user_name }}" soft nproc 16384
          "{{ was_user_name }}" hard nproc 16384
        with_items: 
          - /etc/security/limits.d/90-nproc.conf
          - /etc/security/limits.d/20-nproc.conf

    - name: If the files exists and ulimit -n, set the nofile 
      blockinfile:
        path: /etc/profile
        insertafter: ulimit -n
        block: |
          # - ofile - maximum number of open files
          "{{ was_user_name }}" soft nofile 65536
          "{{ was_user_name }}" hard nofile 65536

    - name: Set umask 077 in /etc/profild
      lineinfile:
        path: /etc/profile
        line: umask 077

    - name: Reboot the server
      shell: /sbin/reboot &
      async: 0
      poll: 0
      ignore_errors: true

    - name: Wait for the server to rebooting
      local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300

      #- name: WAS tuning

        #    - name: Time needs to be syncronized

