---
# Creates ec2 instance, then installs LAMP stack in it. Follows up with a current WordPress install complete with theme.

- hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    awsregion: us-east-1
    instancesize: t2.micro
    instancename: webserver-wp-gjp
    keypair: ec2-ol-mgt
    amitouse: ami-43745729 # CentOS 7.3
    numberofservers: 1
    subnettolaunchin: subnet-c7b3549c
    
  tasks:
      - name: Launch ec2 instance
        ec2:
          key_name: "{{keypair}}"
          instance_type: "{{instancesize}}"
          image: "{{amitouse}}"
          wait: yes
          group: webserver-sg
          count: "{{numberofservers}}"
          vpc_subnet_id: "{{subnettolaunchin}}"
          assign_public_ip: yes
          region: "{{awsregion}}"
          state: present
          instance_tags:
             Name: "{{instancename}}"
             Application: webserver
        register: ec2
             
      - name: Wait until port 22 becomes active
        local_action: wait_for host={{ item.public_ip }} port=22 state=started
        with_items: "{{ ec2.instances }}"
       
      - name: Force refresh inventory
        meta: refresh_inventory

      - name: Public IP of instance is 
        debug:
          var: ec2.instances[0].public_ip
