# Build a Wordpress install on a RHEL/CentOS staging server
# Components installed: httpd, php, php-mysql, wp-cli, mysql, mysqld

- hosts: tag_Application_webserver
  become: True
  become_user: root
  gather_facts: No

  tasks:
    - name: Update the packages to the latest
      yum: name=* state=latest
