---
- name: Provision instances
  hosts: localhost
  connection: local
  gather_facts: False

  # load AWS variables from this group vars file
  vars_files:
  - group_vars/all

  - name: Launch ec2 instance
    ec2:
      key_name: "{{keypair}}"
      instance_type: "{{instancesize}}"
      image: "{{amitouse}}"
      wait: yes
      count: "{{numberofservers}}"
      vpc_subnet_id: "{{subnettolaunchin}}"
      assign_public_ip: yes
      region: "{{awsregion}}"
      state: present
      instance_tags: "{'ansible_group':'jboss', 'type':'{{ instancesize }}',  'Name':'oteemo-jboss'}"
      register: ec2
             
  - name: Wait until port 22 becomes active
    local_action: wait_for host={{ item.public_ip }} port=22 state=started
    with_items: "{{ ec2.instances }}"
       
  - name: Force refresh inventory
    meta: refresh_inventory
