---
# This playbook deploys two simple applications to JBoss server. 

- hosts: tag_Name_jboss_ticketmonster
  become: yes

  roles:
# Optionally, (re)deploy JBoss here	  
    - jboss-standalone
    - java-app
